### ISSUE TITLE
Local Forecast no longer working - 404

### ISSUE THREAD

**Issue by lightningjim** [vbguyny/ws4kp#14] opened 2018-08-14 18:14 UTC
Looks like Weather Underground changed their API as the Local Forecast lookup is now pulling a 404
I'll look for the new version myself on my own time as well.

**Comment by vbguyny** [comment] 2018-08-14 23:52
Hello @lightningjim, Weather Underground is used for the Almanac page (that is why it says "No Data").  The local forecast is working for my area (Zipcode: 11763).  Please try again or let me know what location you are testing that is giving you an error.
Thanks!

**Comment by lightningjim** [comment] 2018-08-15 14:53
73108

**Comment by vbguyny** [comment] 2018-08-16 00:08
@lightningjim Thanks for that! I see that the issue is related to cities with more than one word.  For example, "Medford" works however "Oklahoma City" does not.  I'll look into this further and get back to you.

**Comment by vbguyny** [comment] 2018-08-16 00:29
Ok, the issues has been fixed in version 1.33 which is now live!

**Closed by vbguyny** 2018-08-16 00:29 UTC
