### ISSUE TITLE
Time incorrect after leaving DST

### ISSUE THREAD

**Issue by nivex** [vbguyny/ws4kp#47] opened 2020-11-01 12:40 UTC
WS4K+ appears to be ignoring system time and displaying the wrong time after the recent return to standard time.

![weatherstar-time](https://user-images.githubusercontent.com/3833404/97803020-650a5900-1c15-11eb-8863-075d652e3960.png)

**Comment by vbguyny** [comment] 2020-11-01 13:40
@nivex yep, I see that has an issue on my end as well.  I'll look into it and get back to you!  Thanks for reporting it :)

**Comment by vbguyny** [comment] 2020-11-01 14:13
@nivex Ok, the issue is fixed in 
![Untitled](https://user-images.githubusercontent.com/871502/97805115-1d3dfe80-1c22-11eb-8398-09ecc1d54255.png) which I pushed to the live site.

Due to an issue where Chrome wasn't correctly getting the time zone for some regions in the US that don't use DST I am pulling the info from NOAA's weather.org site.  However, for some reason they have the wrong time zone on their site next to the field "Last Update".  I patched the WeatherStar 4000+ to instead look at the "Forecast Valid" field instead.
https://github.com/vbguyny/ws4kp/commit/d4d3d6e6e05ef4c6ed25497a90189f3e09d9f351

**Closed by vbguyny** 2020-11-01 14:13 UTC
Labels: bug
